# x=100
try:
    print(x)
except:
    print("Something went wrong")
finally:
    print("the 'try exception' is finisehd")